service: default

runtime: nodejs20
instance_class: F4_1G

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 50ms

handlers:
- url: /
  secure: always
  redirect_http_response_code: 301
  script: auto

runtime_config:
  start_command: npm start
