service: backend

runtime: nodejs20
instance_class: F4_1G

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 5
  min_pending_latency: 30ms
  max_pending_latency: 50ms

handlers:
- url: /backend/.*
  script: auto
