// InitialState.js
const initialFormData = {
  eventId: '',
  title: '',
  description: '',
  emoji: '',
  organisedBy: [],
  startDate: new Date(),
  endDate: new Date(),
  marketingProgramInstanceId: '',
  eventType: '',
  region: [],
  subRegion: [],
  country: [],
  activityOwner: [],
  speakers: [],
  eventSeries: 'no',
  emailLanguage: 'English',
  emailText: '',
  languagesAndTemplates: [],
  customerUse: 'yes',
  okr: [],
  gep: [],
  audiencePersona: [],
  audienceSeniority: [],
  accountSectors: '',
  accountSegments: {},
  maxEventCapacity: '',
  peopleMeetingCriteria: '',
  landingPageLink: '',
  salesKitLink: '',
  hailoLink: '',
  otherDocumentsLink: '',
  isHighPriority: false,
  marketingActivityType: '',
};

export { initialFormData };
