const initialFormData = {
    eventId: '',
    title: '',
    description: '',
    emoji: '',
    organisedBy: [],
    startDate: new Date(),
    endDate: new Date(),
    marketingProgramInstanceId: '',
    eventType: '',
    region: [],
    subRegion: [],
    country: [],
    activityOwner: [],
    speakers: [],
    eventSeries: 'no',
    emailLanguage: 'English',
    emailText: '',
    languagesAndTemplates: [],
    customerUse: 'yes',
    okr: [],
    gep: [],
    audiencePersona: [],
    audienceSeniority: [],
    accountSectors: '',
    accountSegments: {},
    maxEventCapacity: '',
    peopleMeetingCriteria: '',
    landingPageLink: '',
    salesKitLink: '',
    hailoLink: '',
    otherDocumentsLink: '',
    isHighPriority: false,
    marketingActivityType: '',
  };
  
  const initialContext = {
    monthIndex: 0,
    setMonthIndex: (index) => {},
    smallCalendarMonth: 0,
    setSmallCalendarMonth: (index) => {},
    daySelected: null,
    setDaySelected: (day) => {},
    showEventModal: false,
    setShowEventModal: () => {},
    showEventListModal: false,
    setShowEventListModal: () => {},
    dispatchCalEvent: ({ type, payload }) => {},
    savedEvents: [],
    selectedEvent: null,
    setSelectedEvent: () => {},
    setLabels: () => {},
    labels: [],
    updateLabel: () => {},
    filteredEvents: [],
    sidebarOpen: true,
    toggleSidebar: () => {},
    currentView: 'month',
    setCurrentView: () => {},
    filters: {
      regions: [],
      eventType: [],
      okr: [],
      audienceSeniority: [],
    },
    updateFilters: () => {},
    showEventInfoModal: false,
    setShowInfoEventModal: () => {},
    searchText: '',
    setSearchText: () => {},
    eventDetails: null,
    setEventDetails: () => {},
    formData: initialFormData,
    updateFormData: () => {},
    resetFormData: () => {},
  };
  
  export { initialFormData, initialContext };
  