export function getDummyEventData() {
    return [
      {
        "eventId": "f3241335-3e00-4cd5-8df5-a9e952e3177e",
        "title": "EMEA Marketing event X",
        "description": "This is for internal use only",
        "emoji": "😼",
        "organisedBy": ["Option1"],
        "dropdownValue2": "",
        "marketingActivityType": "",
        "isHighPriority": true,
        "startDate": "2024-01-26T05:44:27.000Z",
        "endDate": "2024-01-26T07:44:27.000Z",
        "marketingProgramInstanceId": "xxxxx",
        "eventType": "Online Event",
        "region": "GLOBAL",
        "subRegion": ["Benelux", "France"],
        "country": ["BE", "NL", "FR"],
        "activityOwner": [],
        "speakers": [],
        "eventSeries": "no",
        "emailLanguage": "English",
        "emailText": "",
        "customerUse": "yes",
        "okr": ["SOURCE DEMAND", "CHAMPION DEI & CULTURE"],
        "gep": ["Not Application (Not tied to Any Global Engagement Plays)", "Reimagine FSI"],
        "activityType": "yes",
        "languagesAndTemplates": [
          { "language": "English", "template": "BLABLABLABLABLA" },
          { "language": "French", "template": "BLABLABLABLABLA" }
        ],
        "audiencePersona": ["Finance Decision Maker", "Finance End User", "Finance Executive", "HR End User"],
        "audienceSeniority": ["Practitioner"],
        "accountSectors": "public sector",
        "accountSegments": { "enterprise": true, "corporate": true, "smb": false },
        "maxEventCapacity": "224234",
        "peopleMeetingCriteria": "234234",
        "landingPageLink": "",
        "salesKitLink": "",
        "hailoLink": "",
        "otherDocumentsLink": ""
      },
      {
        "eventId": "f3291335-3e00-4cd5-8df5-a9e952e3177e",
        "title": "EMEA Marketing event Y",
        "description": "This is for internal use only",
        "emoji": "😼",
        "organisedBy": ["Option1"],
        "dropdownValue2": "",
        "marketingActivityType": "",
        "isHighPriority": true,
        "startDate": "2024-01-26T05:44:27.000Z",
        "endDate": "2024-01-26T08:44:27.000Z",
        "marketingProgramInstanceId": "xxxxx",
        "eventType": "Online Event",
        "region": "GLOBAL",
        "subRegion": ["Benelux", "France"],
        "country": ["BE", "NL", "FR"],
        "activityOwner": [],
        "speakers": [],
        "eventSeries": "no",
        "emailLanguage": "English",
        "emailText": "",
        "customerUse": "yes",
        "okr": ["SOURCE DEMAND", "CHAMPION DEI & CULTURE"],
        "gep": ["Not Application (Not tied to Any Global Engagement Plays)", "Reimagine FSI"],
        "activityType": "yes",
        "languagesAndTemplates": [
          { "language": "English", "template": "BLABLABLABLABLA" },
          { "language": "French", "template": "BLABLABLABLABLA" }
        ],
        "audiencePersona": ["Finance Decision Maker", "Finance End User", "Finance Executive", "HR End User"],
        "audienceSeniority": ["Practitioner"],
        "accountSectors": "public sector",
        "accountSegments": { "enterprise": true, "corporate": true, "smb": false },
        "maxEventCapacity": "224234",
        "peopleMeetingCriteria": "234234",
        "landingPageLink": "",
        "salesKitLink": "",
        "hailoLink": "",
        "otherDocumentsLink": ""
      },
      {
        "eventId": "b5b9a962-b10b-4229-b1c3-3991e5fcf365",
        "title": "EMEA Marketing event X",
        "description": "This is for internal use only",
        "emoji": "😼",
        "organisedBy": ["Option1"],
        "dropdownValue2": "",
        "marketingActivityType": "",
        "isHighPriority": true,
        "startDate": "2024-01-30T08:44:27.000Z",
        "endDate": "2024-01-30T09:20:27.000Z",
        "marketingProgramInstanceId": "xxxxx",
        "eventType": "Physical Event",
        "region": "EMEA",
        "subRegion": ["Benelux"],
        "country": ["BE", "NL"],
        "activityOwner": [],
        "speakers": [],
        "eventSeries": "no",
        "emailLanguage": "English",
        "emailText": "",
        "customerUse": "yes",
        "okr": ["SOURCE DEMAND", "CHAMPION DEI & CULTURE"],
        "gep": ["Not Application (Not tied to Any Global Engagement Plays)", "Reimagine FSI"],
        "activityType": "yes",
        "languagesAndTemplates": [
          { "language": "English", "template": "BLABLABLABLABLA" },
          { "language": "French", "template": "BLABLABLABLABLA" }
        ],
        "audiencePersona": ["Finance Decision Maker", "Finance End User", "Finance Executive", "HR End User"],
        "audienceSeniority": ["Practitioner"],
        "accountSectors": "public sector",
        "accountSegments": { "enterprise": true, "corporate": true, "smb": false },
        "maxEventCapacity": "224234",
        "peopleMeetingCriteria": "234234",
        "landingPageLink": "http://random.co.uk",
        "salesKitLink": "",
        "hailoLink": "",
        "otherDocumentsLink": ""
      }
    ];
  }
  
